# docker build --no-cache --network=host -t durumi .
# 이후 : docker-compose up
# 방화벽 설정으로 실행 안될때 iptables 초기화 
# sudo iptables -t filter -F &&
# sudo iptables -t filter -X
# systemctl restart docker

# sudo iptables -t filter -F && sudo iptables -t filter -X && sudo systemctl restart docker 

version: "2"

services:
  durumi:
    image: durumi
    container_name: durumi_service
    volumes:
      - ../volumes:/home/
    working_dir: /home/durumi/
    command: >
      bash -c "python3 manage.py makemigrations durumiApp --noinput
      && python3 manage.py migrate --noinput
      && python3 manage.py collectstatic --noinput
      && gunicorn durumi.wsgi:application -b 0.0.0.0:8000"
    ports:
      - "8000:8000"
    expose:
      - "8000"
  nginx:
    image: nginx
    container_name: nginx_service
    volumes:
      - ../volumes-nginx:/etc/nginx/conf.d
      - ../volumes/.static_root/:/static
    ports:
      - "80:80"
    depends_on:
      - durumi
