#docker-compose run durumi django-admin.py startproject durumi
version: "2"

services:
  durumi:
    image: durumi
    volumes: 
      - /home/synod2/synod2/durumi/workspace/volumes:/home/
    command:
      - bash
      - -c
      - python3 /home/durumi/manage.py runserver 0:8000
    ports: 
      - "8000:8000"
      
  ----------------------
      
  nginx:
    image: nginx
    volumes: 
      - /home/synod2/synod2/durumi/workspace/volumes-nginx:/etc/nginx/conf.d
    ports:
      - "80:80"
    depends_on : 
      - durumi